Techs & Footer
wolox-training/lfm-android pull request #8
Opened 2019-09-27 21:43 UTC by lfmontesanto

**Summary:** 
Created : 
- List Header 

- TechLists (Back and front)

- Footer

**ScreenShots**: 

![image](https://user-images.githubusercontent.com/43759054/65803857-502bde00-e156-11e9-81ab-2d38af2065d4.png)

![image](https://user-images.githubusercontent.com/43759054/65803871-5a4ddc80-e156-11e9-9cfb-ecc7632f2055.png)

2019-10-01 15:05 UTC, nmartinelli23 requested changes

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/index.html
> +    <img class="header-logo" src="assets/triangle.svg">
Missing alt attribute.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/index.html
> +        <img class="tech-logo" src="assets/react_icon.svg">
Same here. Add this to every img tag please :)

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/index.html
> +</html>
Missing end of file blank line.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/public/stylesheets
> +Errno::ENOENT: No such file or directory @ rb_sysopen -
What is this?

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/application.scss
> +@import'footer';
Missing blank line at the end.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/footer.scss
> +  display: flex;
Sort instructions alphabetically for further reading and subsequent search for instructions.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/footer.scss
> +    margin: 10px 0px 10px 0px;
margin: 10px 0;

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/footer.scss
> +}
EOF

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/header.scss
> +      margin-left: -18px;
Try avoiding negative values.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/tech-list.scss
> +}
EOF

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/tech.scss
> +    width: 100px;
replace this with:
max-width: 100px;
width: 100%;
Same in height.

2019-10-01 15:05 UTC, nmartinelli23 commented on TrainingMaquetado/scss/tech.scss
> +}
EOF

2019-10-01 15:05 UTC, nmartinelli23 commented on public/stylesheets
> +/*
Why this is twice?

2019-11-28 17:03 UTC, Dorian30 requested changes

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/index.html
> +    <h1 class="header-title">Front-End Tools</h1>
You should have only one `h1` for each page. For example, if you had a tittle like `Wolox Techs` that would be your main title. 

With that in mind you should wrap both your front end & back end titles inside a h2 tag

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/index.html
> +    <h1 class="header-title">Back-End Tools</h1>
Same

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/index.html
> +    <img class="header-logo" src="assets/triangle.svg" alt="Title decorator">
We use pseudo classes for these type of things. If your image does not add any context to your page and it's only to decorate a section, you can use a pseudo class (after or before) instead.

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/index.html
> +    <img class="header-logo" src="assets/triangle.svg" alt = "Title decorator">
Same

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/index.html
> +    <h2 class="footer-slogan">WE ARE GAME CHANGERS</h2>
Good work naming your classes. Just one thing, use a property instead to make your text uppercase.

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/header.scss
> +      margin-left: -18px;
We don't use margin-left or top 'cause it's more troublesome when you have to make your layout responsive. I don't see why you would need to set a negative value here.

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/footer.scss
> +  background: #00ADEE;
Make a `colors.scss` file for this where you can hold these type of values.

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/footer.scss
> +    margin: 10px 0;
We don't use margin top for responsive purposes. If you need to make a gap between to elements then use margin bottom in your upper tag instead. 

Also, avoid nesting classes. this increases their specificity and it can be troublesome if you want to change some property on them further down the road. You already being specific by giving them unique names.

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/footer.scss
> +    margin: 10px 0px 10px 0px;
Same 

Also, a quick note. You can use a shorthand whenever you need something like this, for example:

```css
  margin: 10px 0;
```

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/footer.scss
> +    margin: 10px 10px 10px 0px;
Same

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/footer.scss
> +  .footer-copyright{
Same, there is no need to nest classes

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/header.scss
> +    .header-title{
Avoid nesting classes

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/header.scss
> +    margin: 10px 0px 0px 20px;
Same, don't use margin top

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/header.scss
> +    .header-logo{
Same. Also leave a white space between your class name and the bracket 

```suggestion
    .header-logo {
```

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/styles.scss
> +}
You are missing the white line at the end of this file

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech-list.scss
> +  margin: 20px 0px 40px 50px;
Same. Don't use margin top or margin left

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +    border: 1px solid #BED23C;
Hold this value inside a variable in `colors.scss`

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +  .tech-description {
Nested classes

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +  .tech-date {
Same

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +  .tech-logo {
Same

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +  background: #BED23C;
Use a variable :eyes:

2019-11-28 17:03 UTC, Dorian30 commented on TrainingMaquetado/scss/tech.scss
> +  margin: 10px 50px 50px 20px;
Avoid top and left. In almost every scenario you can solve this by using bottom and right in some other element or even padding in your container

2019-11-28 17:03 UTC, Dorian30 commented on public/stylesheets
> +  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - app/sass"; }
What's this ? :eyes:

2020-02-03 14:20 UTC, merged